### ISSUE TITLE
[Security] Workflow releasables.yml is using vulnerable action softprops/action-gh-release

### ISSUE THREAD

**Issue by igibek** [sbergen/Responsible#132]
The workflow releasables.yml is referencing action softprops/action-gh-release using references 91409e712cf565ce9eff10c87a8d1b11b81757ae. However this reference is missing the commit [2cf5c664505721097376937a6b0bcd26758fefc8](https://github.com/softprops/action-gh-release/commits/2cf5c664505721097376937a6b0bcd26758fefc8) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by sbergen** [comment]
Sorry, but the `v1` tag is actually [1e07f4398721186383de40550babbdf2b84acfc5](https://github.com/softprops/action-gh-release/tree/1e07f4398721186383de40550babbdf2b84acfc5), which already uses node-fetch 2.6.1.
